image: continuumio/miniconda3:4.6.14

stages:
  - test

test:
  stage: test
  script:
    - conda config --set always_yes yes
    - conda config --append channels conda-forge
    - conda env create -f environment.yml
    - conda env update -f dev-environment.yml
    - source activate bufrtools
    - pip install -e .
    - pytest bufrtools

lint:
  stage: test
  script:
    - conda config --set always_yes yes
    - conda config --append channels conda-forge
    - conda create --name flakeit python=3.8
    - conda install --name flakeit flake8 flake8-docstrings
    - source activate flakeit
    - flake8 bufrtools
