package:
  name: bufrtools
  version: "1.0.3"

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cftime
    - pandas
    - pyyaml
    - pocean-core >=1.9.3
    - pyarrow

test:
  source_files:
    - bufrtools
  imports:
    - bufrtools

about:
  home: https://github.com/axiom-data-science/bufrtools
  license: MIT
  license_file: LICENSE.txt
  summary: 'A suite of utilities and scripts to forge a BUFR file, or decode one.'
